// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcSBHDMRZFlZB20nFQ0uy03GJKEWBPN0',
    appId: '1:977212658692:web:4b4423b0480c8b6f8b5151',
    messagingSenderId: '977212658692',
    projectId: 'smart-inventory-alsakina-99a9b',
    authDomain: 'smart-inventory-alsakina-99a9b.firebaseapp.com',
    storageBucket: 'smart-inventory-alsakina-99a9b.firebasestorage.app',
    measurementId: 'G-6W486VNXCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJQROaLze7K-sM9mlX-fH3DRsN0iKKEo',
    appId: '1:977212658692:android:2b481ca5d7dea38a8b5151',
    messagingSenderId: '977212658692',
    projectId: 'smart-inventory-alsakina-99a9b',
    storageBucket: 'smart-inventory-alsakina-99a9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwHJGH-ssdFne5OlIiV63yhrhZcFqZaY',
    appId: '1:977212658692:ios:20cd6ab6ea559fb38b5151',
    messagingSenderId: '977212658692',
    projectId: 'smart-inventory-alsakina-99a9b',
    storageBucket: 'smart-inventory-alsakina-99a9b.firebasestorage.app',
    iosBundleId: 'com.example.smartInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIwHJGH-ssdFne5OlIiV63yhrhZcFqZaY',
    appId: '1:977212658692:ios:20cd6ab6ea559fb38b5151',
    messagingSenderId: '977212658692',
    projectId: 'smart-inventory-alsakina-99a9b',
    storageBucket: 'smart-inventory-alsakina-99a9b.firebasestorage.app',
    iosBundleId: 'com.example.smartInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCcSBHDMRZFlZB20nFQ0uy03GJKEWBPN0',
    appId: '1:977212658692:web:a0c3a2b5287871be8b5151',
    messagingSenderId: '977212658692',
    projectId: 'smart-inventory-alsakina-99a9b',
    authDomain: 'smart-inventory-alsakina-99a9b.firebaseapp.com',
    storageBucket: 'smart-inventory-alsakina-99a9b.firebasestorage.app',
    measurementId: 'G-5EF7Q3NMT6',
  );

}